export const videoReferences = [
  {
    title: "An overview of Azure Integration Services | Azure Friday",
    channel: "Microsoft Developer",
    url: "https://www.youtube.com/watch?v=sbqhJsWhKAs",
    chapters: ["platform", "messaging"],
    topics: ["Azure Logic Apps", "Azure Service Bus", "Azure API Management (APIM)"],
  },
  {
    title: "Azure Integration Services Masterclass with Logic Apps & Service Bus",
    channel: "Stephen W. Thomas | AI, Agents & Azure Integration",
    url: "https://www.youtube.com/watch?v=SAifvErWhWM",
    chapters: ["platform", "messaging", "edi"],
    topics: [
      "Azure Logic Apps",
      "Azure Service Bus",
      "Azure Integration Account",
      "Azure API Management (APIM)",
      "Electronic Data Interchange (EDI)",
      "Topics and Subscriptions",
      "Dead-Letter Queues (DLQs)",
      "Correlation IDs",
    ],
  },
  {
    title: "Configure Azure Front Door in front of Azure API Management",
    channel: "Sri Gunnala - Tech Talks",
    url: "https://www.youtube.com/watch?v=fdRhQM6kzoY",
    chapters: ["platform"],
    topics: ["Azure API Management (APIM)", "Azure Front Door Premium"],
  },
  {
    title: "Azure Front Door and WAF with Custom Rules",
    channel: "Rohit Sharma",
    url: "https://www.youtube.com/watch?v=iCN4JbZ9Svk",
    chapters: ["platform", "security"],
    topics: [
      "Azure Front Door Premium",
      "Azure Web Application Firewall (WAF)",
      "IP address filtering",
    ],
  },
  {
    title: "Using Azure Integration Accounts to create a Real EDI Integration Build",
    channel: "Luke Saunders (System Integration)",
    url: "https://www.youtube.com/watch?v=WGYRrf0sEQ4",
    chapters: ["platform", "edi"],
    topics: [
      "Azure Logic Apps",
      "Azure Integration Account",
      "Azure Storage",
      "EDI mapping to a shared internal model",
      "Partner implementation guides & profiles",
      "EDI onboarding, reconciliation & recovery",
    ],
  },
  {
    title: "Azure Storage Services: Blob, Queue, Table, Files, Disk and Storage Tiers",
    channel: "Adam Marczak - Azure for Everyone",
    url: "https://www.youtube.com/watch?v=_Qlkvd4ZQuo",
    chapters: ["platform"],
    topics: ["Azure Storage"],
  },
  {
    title: "Azure SQL Managed Instance overview | Azure SQL for beginners",
    channel: "Microsoft Developer",
    url: "https://www.youtube.com/watch?v=VM0eiOmE35I",
    chapters: ["platform"],
    topics: ["Azure SQL Managed Instance"],
  },
  {
    title: "Master Distributed Tracing in Azure Application Insights & OpenTelemetry",
    channel: "Shervin Montajam",
    url: "https://www.youtube.com/watch?v=wu0Tl6FIr4A",
    chapters: ["platform", "messaging"],
    topics: [
      "Application Insights",
      "Azure Functions / Function Apps",
      "Azure Service Bus Queues",
      "Correlation IDs",
      "Message ID / Interface ID",
    ],
  },
  {
    title: "Microsoft Azure Log Analytics Workspace | Detailed Tutorial",
    channel: "Concepts Work",
    url: "https://www.youtube.com/watch?v=2ZZrNiXxk28",
    chapters: ["platform"],
    topics: ["Log Analytics"],
  },
  {
    title: "Learn Kusto Query Language from scratch (KQL)",
    channel: "Concepts Work",
    url: "https://www.youtube.com/watch?v=mZLuWijP_xU",
    chapters: ["platform"],
    topics: ["Kusto Query Language (KQL)"],
  },
  {
    title: "Master Azure Monitoring: Azure Monitor, Logs, Metrics & Alerts",
    channel: "Cloud Guru",
    url: "https://www.youtube.com/watch?v=LFkQp_2b704",
    chapters: ["platform", "operations"],
    topics: [
      "Azure Monitor / alerting concepts",
      "Monitoring and alert triage",
      "Monitoring administration",
    ],
  },
  {
    title: "Azure Master Class v3 - Part 2 - Identity",
    channel: "John Savill's Technical Training",
    url: "https://www.youtube.com/watch?v=megA6BPpYqo",
    chapters: ["security"],
    topics: [
      "Microsoft Entra ID / Azure AD fundamentals",
      "Role-based access control (RBAC)",
      "Multifactor authentication (MFA)",
      "Temporary privileged access (PIM)",
    ],
  },
  {
    title: "Azure Key Vault Deep Dive: Private Endpoint, RBAC, Managed Identity",
    channel: "Cloud 360 Training",
    url: "https://www.youtube.com/watch?v=eyXzXRbLDDA",
    chapters: ["security"],
    topics: [
      "Managed Identity",
      "Role-based access control (RBAC)",
      "Private Endpoints",
    ],
  },
  {
    title: "Mastering Azure Private Endpoints: Configuration and DNS Setup Guide",
    channel: "MS Cloud Bros with Jeremy Wallace",
    url: "https://www.youtube.com/watch?v=ABzp8uQajcU",
    chapters: ["security"],
    topics: ["Virtual Network (VNet)", "Private Endpoints", "DNS / network troubleshooting"],
  },
  {
    title: "Azure Private Link - Simply Explained",
    url: "https://www.youtube.com/watch?v=DwSNOnwJ0uw",
    chapters: ["security"],
    topics: [
      "Virtual Network (VNet)",
      "Private Endpoints",
      "ExpressRoute",
      "DNS / network troubleshooting",
    ],
  },
  {
    title: "SSL/TLS Explained in 7 Minutes",
    channel: "Sematext",
    url: "https://www.youtube.com/watch?v=67Kfsmy_frM",
    chapters: ["security"],
    topics: ["TLS / HTTPS"],
  },
  {
    title: "Monitoring SSL expiration in Azure",
    channel: "Visus LLC",
    url: "https://www.youtube.com/watch?v=ivMWPPCDlGk",
    chapters: ["security", "operations"],
    topics: ["Certificate management & expiry monitoring", "Certificate monitoring"],
  },
  {
    title: "Azure Service Bus queues, topics and subscriptions",
    channel: "Harshalkumar Jain",
    url: "https://www.youtube.com/watch?v=hvpapwK8JZ0",
    chapters: ["messaging"],
    topics: [
      "Azure Service Bus Queues",
      "Topics and Subscriptions",
      "Publish / Subscribe architecture",
      "Asynchronous messaging",
      "Queue administration",
    ],
  },
  {
    title: "Azure Service Bus-Replay Messages-Part 1 (Dead Letter Queue)",
    channel: "Sandro Pereira",
    url: "https://www.youtube.com/watch?v=JfA4iQaljH0",
    chapters: ["messaging", "operations"],
    topics: [
      "Dead-Letter Queues (DLQs)",
      "Handling messages that keep failing",
      "Delivery count / Max delivery count",
      "Message retries and reprocessing",
      "Standard message reprocessing",
      "Bulk reprocessing concepts",
    ],
  },
  {
    title: "RabbitMQ exchanges, dead-letter exchanges and acknowledgements",
    channel: "jumpstartCS",
    url: "https://www.youtube.com/watch?v=M7Mg7izbi7w",
    chapters: ["messaging"],
    topics: ["RabbitMQ", "Handling messages that keep failing"],
  },
  {
    title: "Integrating Azure Logic Apps Workflows with RabbitMQ",
    channel: "Harold Campos",
    url: "https://www.youtube.com/watch?v=KSfvYW9j_mc",
    chapters: ["messaging"],
    topics: ["RabbitMQ"],
  },
  {
    title: "Messaging - RabbitMQ, Azure (Service Bus), Docker and Azure Functions",
    channel: "Pusher",
    url: "https://www.youtube.com/watch?v=zfmjJw3zDZQ",
    chapters: ["messaging"],
    topics: [
      "Azure Service Bus Queues",
      "RabbitMQ",
      "RabbitMQ-to-Azure-Service Bus integration",
      "Publish / Subscribe architecture",
      "Asynchronous messaging",
    ],
  },
  {
    title: "Retry Pattern Explained: Backoff, Jitter & Idempotency",
    channel: "FullStackDev",
    url: "https://www.youtube.com/watch?v=I2di1k53VIc",
    chapters: ["messaging"],
    topics: ["Retry patterns", "Exponential backoff", "Safe retries and idempotency"],
  },
  {
    title: "Claim-Check Pattern - Azure Design Patterns",
    channel: "Hussein Awad",
    url: "https://www.youtube.com/watch?v=t_yZWB0S5tM",
    chapters: ["messaging"],
    topics: ["Large messages with the claim-check pattern"],
  },
  {
    title: "ServiceNow Incident Management Overview: Definition, Roles, Priority & ITSM",
    channel: "Palni Inc",
    url: "https://www.youtube.com/watch?v=6hC0Ujyaico",
    chapters: ["operations"],
    topics: ["ServiceNow", "Incident Management", "P1 / P2 / P3 / P4 classification"],
  },
  {
    title: "Service Catalog & Request Management",
    channel: "ServiceNowMadeEfficient",
    url: "https://www.youtube.com/watch?v=iREvytGjHKs",
    chapters: ["operations"],
    topics: ["ServiceNow", "Service Request handling"],
  },
  {
    title: "SLA in ServiceNow | SLA configuration",
    channel: "Learn Tech with Ravi",
    url: "https://www.youtube.com/watch?v=aR4kmvzJ2A8",
    chapters: ["operations"],
    topics: ["ServiceNow", "Service-level agreement (SLA) tracking"],
  },
  {
    title: "Major Incident Management overview",
    channel: "ServiceNow Documentation",
    url: "https://www.youtube.com/watch?v=Q6elypm6wNI",
    chapters: ["operations"],
    topics: ["Major Incident Management", "Incident Management"],
  },
  {
    title: "What Does IT Support Do? Level 1, Level 2, Level 3 Escalations",
    channel: "Tech With Emilio",
    url: "https://www.youtube.com/watch?v=AfeuTK2SF_I",
    chapters: ["operations"],
    topics: ["Level 1 and 2 troubleshooting", "Level 3 escalation"],
  },
  {
    title: "EDI (AS2, X12 & EDIFACT) with Azure Logic Apps Standard & API Management",
    channel: "Turbo360",
    url: "https://www.youtube.com/watch?v=1rpnN-alddg",
    chapters: ["platform", "edi"],
    topics: [
      "Azure API Management (APIM)",
      "Electronic Data Interchange (EDI)",
      "X12 transaction sets",
      "UN/EDIFACT message structure",
      "AS2, SFTP & EDI transport",
      "EDI onboarding, reconciliation & recovery",
    ],
  },
  {
    title: "What is EDI? From Origins to its Critical Role in Modern Global Supply Chains",
    url: "https://www.youtube.com/watch?v=H90_2KKb8-Q",
    chapters: ["edi"],
    topics: [
      "Electronic Data Interchange (EDI)",
      "Common EDI messages & business flows",
      "X12 transaction sets",
      "UN/EDIFACT message structure",
    ],
  },
  {
    title: "What is 850 Purchase Order | X12 850 Transaction Set in EDI",
    channel: "Tech EDI",
    url: "https://www.youtube.com/watch?v=MHWGmjS0mXU",
    chapters: ["edi"],
    topics: ["Common EDI messages & business flows", "X12 transaction sets"],
  },
  {
    title: "In-depth tutorial on EDI X12 Message Structure - ISA Header & IEA Footer",
    channel: "All About EDI & Cloud",
    url: "https://www.youtube.com/watch?v=a0rMapLmk5A",
    chapters: ["edi"],
    topics: ["X12 envelopes, versions & control numbers"],
  },
  {
    title: "What is 997 X12 Transaction Set | Functional Acknowledgement 997",
    channel: "Tech EDI",
    url: "https://www.youtube.com/watch?v=9qSfEHpCrCI",
    chapters: ["edi"],
    topics: ["EDI acknowledgment layers"],
  },
  {
    title: "UN/EDIFACT CONTRL Acknowledgment",
    channel: "rob4edidev",
    url: "https://www.youtube.com/watch?v=edg_st9U6Z8",
    chapters: ["edi"],
    topics: ["EDI acknowledgment layers"],
  },
  {
    title: "EDI via AS2? What does it mean?",
    channel: "EDI Support LLC",
    url: "https://www.youtube.com/watch?v=UR86a3xeG00",
    chapters: ["edi"],
    topics: ["AS2, SFTP & EDI transport"],
  },
  {
    title: "What is GS1? The System Behind Barcodes Explained",
    channel: "EDI SIMPLIFIED",
    url: "https://www.youtube.com/watch?v=AcUMfeckx4k",
    chapters: ["edi"],
    topics: ["Supply-chain identifiers: GTIN, GLN & SSCC"],
  },
  {
    title: "Use of the Serial Shipping Container Code (SSCC) in the retail sector",
    channel: "GS1",
    url: "https://www.youtube.com/watch?v=R2pNIbI6kAs",
    chapters: ["edi"],
    topics: ["Supply-chain identifiers: GTIN, GLN & SSCC"],
  },
  {
    title: "Demystifying EPCIS",
    channel: "GS1 US",
    url: "https://www.youtube.com/watch?v=D5pPtEu2YvI",
    chapters: ["edi"],
    topics: ["Supply-chain events: EPCIS and EDI"],
  },
];
